x-gpu: &x-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

x-gui: &x-gui
  build:
    context: .
    dockerfile: gui/Dockerfile
  ports:
    - "127.0.0.1:7860:7860"

secrets:
  hf_token:
    environment: "HF_TOKEN"

services:
  stable-audio-controlnet:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
    <<: *x-gpu
    tty: true
    stdin_open: true

  gui:
    <<: *x-gui
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
      - GRADIO_SERVER_NAME=127.0.0.1
      - GRADIO_SERVER_PORT=7860

  gui-gpu:
    <<: [*x-gui, *x-gpu]
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
      - GRADIO_SERVER_NAME=127.0.0.1
      - GRADIO_SERVER_PORT=7860
      - CUDA_VISIBLE_DEVICES=0
