x-gpu: &x-gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

x-gui: &x-gui
  build:
    context: .
    dockerfile: gui/Dockerfile
  ports:
    - "127.0.0.1:7860:7860"

secrets:
  hf_token:
    environment: "HF_TOKEN"

services:
  stable-audio-controlnet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: ${USER:-docker}
    volumes:
      - ./main:/app/main:ro
      - ./scripts:/app/scripts:ro
      - ./ckpts:/app/ckpts
      - ./data:/app/data
      - ./exp:/app/exp:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./train.py:/app/train.py:ro
      - ./eval.py:/app/eval.py:ro
      - ./logs:/app/logs
      - ./out:/app/out
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
    <<: *x-gpu
    user: "1000:1000"
    tty: true
    stdin_open: true

  gui:
    <<: *x-gui
    volumes:
      - ./main:/app/main:ro
      - ./gui:/app/gui:ro
      - ./ckpts:/app/ckpts:ro
      - ./data:/app/data:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./exp:/app/exp:ro
      - ./out:/app/out
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
      - GRADIO_SERVER_NAME=127.0.0.1
      - GRADIO_SERVER_PORT=7860
    user: "1000:1000"

  gui-gpu:
    <<: [*x-gui, *x-gpu]
    volumes:
      - ./main:/app/main:ro
      - ./gui:/app/gui:ro
      - ./ckpts:/app/ckpts:ro
      - ./data:/app/data:ro
      - ./config.yaml:/app/config.yaml:ro
      - ./exp:/app/exp:ro
      - ./out:/app/out
    environment:
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
      - GRADIO_SERVER_NAME=127.0.0.1
      - GRADIO_SERVER_PORT=7860
      - CUDA_VISIBLE_DEVICES=0
    user: "1000:1000"
